//! Awareness Mesh — background watcher system for logs, email, code, calendar.
//! Each watcher: poll via Connect sister → parse via Data sister →
//! check against profile beliefs → alert if threshold crossed.
//!
//! Why isn't a sister doing this? This orchestrates ACROSS sisters (Connect
//! for polling, Data for parsing, Memory for context). No single sister owns
//! the awareness pipeline.

use crate::sisters::SistersHandle;
use std::sync::{Mutex, OnceLock};

/// Global awareness state — persists across sessions.
pub static GLOBAL_AWARENESS: OnceLock<Mutex<AwarenessState>> = OnceLock::new();

pub fn awareness_state() -> &'static Mutex<AwarenessState> {
    GLOBAL_AWARENESS.get_or_init(|| Mutex::new(AwarenessState::new()))
}

/// Type of watcher in the mesh.
#[derive(Debug, Clone, PartialEq)]
pub enum WatcherType {
    Log,
    Email,
    Code,
    Calendar,
    Endpoint,
    Custom(String),
}

/// A single watcher configuration.
#[derive(Debug, Clone)]
pub struct Watcher {
    pub name: String,
    pub watcher_type: WatcherType,
    pub target: String,
    pub interval_secs: u64,
    pub threshold: AlertThreshold,
    pub enabled: bool,
}

/// When to fire an alert.
#[derive(Debug, Clone)]
pub struct AlertThreshold {
    pub condition: String,
    pub severity: AlertSeverity,
}

/// Alert severity levels.
#[derive(Debug, Clone, PartialEq, Ord, PartialOrd, Eq)]
pub enum AlertSeverity {
    Info,
    Important,
    Urgent,
}

/// An alert generated by a watcher.
#[derive(Debug, Clone)]
pub struct AwarenessAlert {
    pub watcher_name: String,
    pub severity: AlertSeverity,
    pub title: String,
    pub detail: String,
    pub timestamp: String,
}

/// Accumulated awareness state.
#[derive(Debug)]
pub struct AwarenessState {
    pub alerts: Vec<AwarenessAlert>,
    pub last_sweep: Option<String>,
    pub watchers_active: usize,
}

impl AwarenessState {
    pub fn new() -> Self {
        Self {
            alerts: Vec::new(),
            last_sweep: None,
            watchers_active: 0,
        }
    }

    /// Add an alert to the accumulator.
    pub fn push_alert(&mut self, alert: AwarenessAlert) {
        self.alerts.push(alert);
    }

    /// Drain all alerts (consumed by morning briefing).
    pub fn drain_alerts(&mut self) -> Vec<AwarenessAlert> {
        std::mem::take(&mut self.alerts)
    }

    /// Count pending alerts.
    pub fn pending_count(&self) -> usize {
        self.alerts.len()
    }
}

/// Default watchers for dev profile.
pub fn default_dev_watchers() -> Vec<Watcher> {
    vec![
        Watcher {
            name: "git_changes".into(),
            watcher_type: WatcherType::Code,
            target: "git log --oneline -10".into(),
            interval_secs: 300,
            threshold: AlertThreshold {
                condition: "new commits since last check".into(),
                severity: AlertSeverity::Info,
            },
            enabled: true,
        },
        Watcher {
            name: "test_status".into(),
            watcher_type: WatcherType::Code,
            target: "cargo test --no-run".into(),
            interval_secs: 600,
            threshold: AlertThreshold {
                condition: "compilation failure".into(),
                severity: AlertSeverity::Important,
            },
            enabled: true,
        },
    ]
}

/// Default watchers for devops profile.
pub fn default_devops_watchers() -> Vec<Watcher> {
    vec![
        Watcher {
            name: "endpoint_health".into(),
            watcher_type: WatcherType::Endpoint,
            target: "health check endpoints".into(),
            interval_secs: 60,
            threshold: AlertThreshold {
                condition: "HTTP status != 200".into(),
                severity: AlertSeverity::Urgent,
            },
            enabled: true,
        },
        Watcher {
            name: "disk_usage".into(),
            watcher_type: WatcherType::Log,
            target: "df -h".into(),
            interval_secs: 300,
            threshold: AlertThreshold {
                condition: "usage > 80%".into(),
                severity: AlertSeverity::Important,
            },
            enabled: true,
        },
    ]
}

/// Run a sweep of all watchers. Called from Dream State idle handler.
pub async fn run_sweep(
    watchers: &[Watcher],
    sisters: &SistersHandle,
) -> Vec<AwarenessAlert> {
    let mut alerts = Vec::new();
    let now = chrono::Utc::now().to_rfc3339();

    for watcher in watchers.iter().filter(|w| w.enabled) {
        let result = poll_watcher(watcher, sisters).await;
        if let Some(alert_detail) = result {
            alerts.push(AwarenessAlert {
                watcher_name: watcher.name.clone(),
                severity: watcher.threshold.severity.clone(),
                title: format!("[{}] {}", watcher.name, watcher.threshold.condition),
                detail: alert_detail,
                timestamp: now.clone(),
            });
        }
    }

    // Store alerts in global state
    if let Ok(mut state) = awareness_state().lock() {
        for alert in &alerts {
            state.push_alert(alert.clone());
        }
        state.last_sweep = Some(now);
        state.watchers_active = watchers.iter().filter(|w| w.enabled).count();
    }

    if !alerts.is_empty() {
        eprintln!("[hydra:awareness] Sweep found {} alerts", alerts.len());
    }

    alerts
}

/// Poll a single watcher via Connect sister.
async fn poll_watcher(
    watcher: &Watcher,
    sisters: &SistersHandle,
) -> Option<String> {
    match watcher.watcher_type {
        WatcherType::Endpoint => {
            // Use Connect sister to check endpoint health
            let content = format!("[awareness-poll] endpoint: {}", watcher.target);
            sisters.memory_workspace_add(&content, "awareness-mesh").await;
            // In production: call Connect sister's health check tool
            // For now: record the poll attempt
            None
        }
        WatcherType::Code => {
            let content = format!("[awareness-poll] code: {}", watcher.target);
            sisters.memory_workspace_add(&content, "awareness-mesh").await;
            None
        }
        WatcherType::Log => {
            let content = format!("[awareness-poll] log: {}", watcher.target);
            sisters.memory_workspace_add(&content, "awareness-mesh").await;
            None
        }
        _ => None,
    }
}

/// Get watchers for a profile name.
pub fn watchers_for_profile(profile_name: &str) -> Vec<Watcher> {
    match profile_name {
        "dev" => default_dev_watchers(),
        "devops" | "infra" => default_devops_watchers(),
        _ => Vec::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_awareness_state() {
        let mut state = AwarenessState::new();
        assert_eq!(state.pending_count(), 0);
        state.push_alert(AwarenessAlert {
            watcher_name: "test".into(),
            severity: AlertSeverity::Info,
            title: "test alert".into(),
            detail: "detail".into(),
            timestamp: "now".into(),
        });
        assert_eq!(state.pending_count(), 1);
        let drained = state.drain_alerts();
        assert_eq!(drained.len(), 1);
        assert_eq!(state.pending_count(), 0);
    }

    #[test]
    fn test_default_watchers() {
        let w = default_dev_watchers();
        assert!(!w.is_empty());
        assert!(w.iter().all(|w| w.enabled));
    }

    #[test]
    fn test_watchers_for_profile() {
        assert!(!watchers_for_profile("dev").is_empty());
        assert!(!watchers_for_profile("devops").is_empty());
        assert!(watchers_for_profile("unknown_profile").is_empty());
    }

    #[test]
    fn test_severity_ordering() {
        assert!(AlertSeverity::Urgent > AlertSeverity::Important);
        assert!(AlertSeverity::Important > AlertSeverity::Info);
    }
}
