//! Creative Engine — cross-pollination, constraint inversion, pattern transfer,
//! adversarial creativity. Generates novel ideas from existing beliefs.
//!
//! Why isn't a sister doing this? This orchestrates ACROSS belief domains and
//! reasoning strategies. No single sister has cross-domain creative capacity.

use hydra_native_state::operational_profile::ProfileBelief;

/// A creative idea generated by the engine.
#[derive(Debug, Clone)]
pub struct CreativeIdea {
    pub title: String,
    pub description: String,
    pub technique: CreativeTechnique,
    pub source_beliefs: Vec<String>,
    pub novelty_score: f64,
    pub feasibility_score: f64,
}

/// Technique used to generate the idea.
#[derive(Debug, Clone, PartialEq)]
pub enum CreativeTechnique {
    CrossPollination,    // Inject belief from random different domain
    ConstraintInversion, // Flip an assumption
    PatternTransfer,     // Apply solution from another domain
    AdversarialCreativity, // "What would your competitor do?"
    Combination,         // Merge two unrelated beliefs
}

/// Generate creative ideas from a set of beliefs.
pub fn generate_ideas(
    beliefs: &[ProfileBelief],
    query: &str,
    max_ideas: usize,
) -> Vec<CreativeIdea> {
    let mut ideas = Vec::new();

    if beliefs.len() < 3 {
        return ideas;
    }

    // Technique 1: Cross-pollination — find beliefs from unrelated domains
    let domains = collect_domains(beliefs);
    if domains.len() >= 2 {
        let domain_pairs: Vec<(&String, &String)> = domains.keys()
            .zip(domains.keys().skip(1))
            .take(max_ideas / 2)
            .collect();

        for (d1, d2) in domain_pairs {
            if let (Some(b1), Some(b2)) = (domains[d1].first(), domains[d2].first()) {
                ideas.push(CreativeIdea {
                    title: format!("Cross-pollination: {} × {}", d1, d2),
                    description: format!(
                        "What if we applied '{}' thinking to the '{}' domain? \
                         Specifically: {} meets {}",
                        d1, d2, truncate(&b1.content, 50), truncate(&b2.content, 50),
                    ),
                    technique: CreativeTechnique::CrossPollination,
                    source_beliefs: vec![b1.content.clone(), b2.content.clone()],
                    novelty_score: 0.7,
                    feasibility_score: 0.5,
                });
            }
        }
    }

    // Technique 2: Constraint inversion — flip assumptions in high-confidence beliefs
    for belief in beliefs.iter().filter(|b| b.confidence >= 0.85).take(max_ideas / 2) {
        let inverted = invert_belief(&belief.content);
        ideas.push(CreativeIdea {
            title: format!("What if the opposite: {}", truncate(&belief.topic, 30)),
            description: format!(
                "Current belief: '{}'\nInverted: '{}'\nWhat opportunities does the inversion reveal?",
                truncate(&belief.content, 80), inverted,
            ),
            technique: CreativeTechnique::ConstraintInversion,
            source_beliefs: vec![belief.content.clone()],
            novelty_score: 0.8,
            feasibility_score: 0.3,
        });
    }

    // Technique 3: Adversarial — what would a competitor do differently?
    if !query.is_empty() {
        ideas.push(CreativeIdea {
            title: "Adversarial perspective".into(),
            description: format!(
                "If a competitor looked at '{}' with completely different beliefs, \
                 what approach would they take? Challenge every assumption in the \
                 current belief set.",
                truncate(query, 60),
            ),
            technique: CreativeTechnique::AdversarialCreativity,
            source_beliefs: vec![],
            novelty_score: 0.9,
            feasibility_score: 0.4,
        });
    }

    ideas.truncate(max_ideas);
    ideas
}

/// Format ideas for display.
pub fn format_ideas(ideas: &[CreativeIdea]) -> String {
    if ideas.is_empty() {
        return "No creative ideas generated — need more belief diversity.".into();
    }
    let mut out = format!("{} creative ideas:\n\n", ideas.len());
    for (i, idea) in ideas.iter().enumerate() {
        out.push_str(&format!(
            "{}. [{}] {}\n   {}\n   Novelty: {:.0}% | Feasibility: {:.0}%\n\n",
            i + 1,
            match idea.technique {
                CreativeTechnique::CrossPollination => "Cross-Domain",
                CreativeTechnique::ConstraintInversion => "Inversion",
                CreativeTechnique::PatternTransfer => "Transfer",
                CreativeTechnique::AdversarialCreativity => "Adversarial",
                CreativeTechnique::Combination => "Combination",
            },
            idea.title,
            idea.description,
            idea.novelty_score * 100.0,
            idea.feasibility_score * 100.0,
        ));
    }
    out
}

fn collect_domains(beliefs: &[ProfileBelief]) -> std::collections::HashMap<String, Vec<&ProfileBelief>> {
    let mut map: std::collections::HashMap<String, Vec<&ProfileBelief>> = std::collections::HashMap::new();
    for b in beliefs {
        let domain = b.topic.split('/').next().unwrap_or("general").to_string();
        map.entry(domain).or_default().push(b);
    }
    map
}

fn invert_belief(content: &str) -> String {
    let inversions = [
        ("always", "never"), ("never", "always"), ("should", "shouldn't"),
        ("best", "worst"), ("increase", "decrease"), ("high", "low"),
        ("strong", "weak"), ("fast", "slow"), ("more", "less"),
    ];
    let mut inverted = content.to_string();
    for (from, to) in &inversions {
        if inverted.to_lowercase().contains(from) {
            inverted = inverted.replacen(from, to, 1);
            break;
        }
    }
    if inverted == content { format!("NOT: {}", content) } else { inverted }
}

fn truncate(s: &str, max: usize) -> &str {
    if s.len() <= max { s } else { &s[..max] }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn b(topic: &str, content: &str) -> ProfileBelief {
        ProfileBelief { topic: topic.into(), content: content.into(), confidence: 0.9 }
    }

    #[test]
    fn test_generate_with_two_domains() {
        let beliefs = vec![
            b("rust/ownership", "Ownership prevents data races"),
            b("rust/testing", "Test everything"),
            b("security/defense", "Defense in depth"),
        ];
        let ideas = generate_ideas(&beliefs, "architecture", 5);
        assert!(!ideas.is_empty());
    }

    #[test]
    fn test_invert_belief() {
        assert!(invert_belief("always use Result").contains("never"));
        assert!(invert_belief("something unique").starts_with("NOT:"));
    }

    #[test]
    fn test_format_ideas() {
        let ideas = vec![CreativeIdea {
            title: "Test".into(), description: "Desc".into(),
            technique: CreativeTechnique::CrossPollination,
            source_beliefs: vec![], novelty_score: 0.7, feasibility_score: 0.5,
        }];
        let formatted = format_ideas(&ideas);
        assert!(formatted.contains("Cross-Domain"));
    }
}
