//! Skill Writer — generates skill TOML files from blueprints.
//! Writes to skills/auto-{name}/genome.toml, loadable by skill_loader.

use super::designer::SkillBlueprint;

/// Write a skill blueprint as a TOML file in the skills directory.
/// Returns the path to the created genome.toml file.
pub fn write_skill(blueprint: &SkillBlueprint) -> Result<String, String> {
    let skills_dir = find_skills_dir()?;
    let skill_dir = skills_dir.join(&blueprint.name);
    std::fs::create_dir_all(&skill_dir)
        .map_err(|e| format!("Cannot create skill dir: {e}"))?;

    let toml = generate_toml(blueprint);
    let path = skill_dir.join("genome.toml");
    std::fs::write(&path, &toml)
        .map_err(|e| format!("Cannot write genome.toml: {e}"))?;

    let path_str = path.display().to_string();
    eprintln!("hydra-evolution: wrote skill to {path_str}");
    Ok(path_str)
}

/// Generate TOML content matching the skill genome format.
fn generate_toml(blueprint: &SkillBlueprint) -> String {
    let mut toml = format!(
        "# Auto-generated by Hydra self-evolution\n# Domain: {}\n# Confidence: {}\n\n",
        blueprint.domain, blueprint.confidence
    );
    for (i, (situation, approach)) in blueprint.approaches.iter().enumerate() {
        toml.push_str(&format!(
            "[[entry]]\nsituation = \"{}\"\napproach = \"{}\"\nconfidence = {}\n\n",
            escape_toml(situation), escape_toml(approach), blueprint.confidence
        ));
        if i >= 9 { break; } // Max 10 entries per skill
    }
    toml
}

fn escape_toml(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn find_skills_dir() -> Result<std::path::PathBuf, String> {
    // Try current dir, then walk up
    let mut dir = std::env::current_dir().unwrap_or_default();
    for _ in 0..6 {
        let skills = dir.join("skills");
        if skills.exists() { return Ok(skills); }
        if !dir.pop() { break; }
    }
    // Fallback: create in home
    let home_skills = dirs::home_dir().unwrap_or_default().join(".hydra/skills");
    std::fs::create_dir_all(&home_skills)
        .map_err(|e| format!("Cannot create skills dir: {e}"))?;
    Ok(home_skills)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_valid_toml() {
        let bp = SkillBlueprint {
            name: "test_skill".into(), domain: "test".into(),
            approaches: vec![("when testing".into(), "run tests".into())],
            confidence: 0.5,
        };
        let toml = generate_toml(&bp);
        assert!(toml.contains("[[entry]]"));
        assert!(toml.contains("when testing"));
        assert!(toml.contains("0.5"));
    }

    #[test]
    fn escapes_special_chars() {
        assert_eq!(escape_toml("hello \"world\""), "hello \\\"world\\\"");
    }
}
