//! Background intelligence scheduler — run tasks between user messages.
//!
//! Phase 5 of the superintelligence plan. Hydra continuously runs background
//! tasks (vulnerability scans, test health checks, memory consolidation)
//! during idle periods between user interactions.

use std::collections::HashMap;
use std::time::{Duration, Instant};

/// Priority determines when a task can run.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum TaskPriority {
    Urgent,   // Run between user messages if possible
    Normal,   // Run during idle (> 30s since last message)
    Low,      // Run during deep idle (> 5 min)
}

/// A registered background task.
#[derive(Debug, Clone)]
pub struct ScheduledTask {
    pub name: String,
    pub interval: Duration,
    pub priority: TaskPriority,
    pub task_type: BackgroundTaskType,
}

/// Types of background tasks Hydra can run.
#[derive(Debug, Clone)]
pub enum BackgroundTaskType {
    /// Scan dependencies for vulnerabilities (Aegis sister)
    VulnerabilityScan,
    /// Check test suite health (Codebase sister)
    TestHealth,
    /// Detect stale branches (Codebase sister)
    StaleBranches,
    /// Consolidate and compress memories (Memory sister)
    MemoryConsolidation,
    /// Identify recurring patterns (Evolve sister)
    PatternCrystallization,
    /// Audit low-confidence beliefs (Cognition sister)
    BeliefAudit,
    /// Sync learnings with federation peers (Comm sister)
    FederationSync,
    /// Generate competence report from outcome tracker
    CompetenceReport,
    /// Reindex codebase source files
    CodebaseIndex,
    /// Custom task with a description
    Custom(String),
}

/// Result of running a background task.
#[derive(Debug, Clone)]
pub struct BackgroundResult {
    pub task_name: String,
    pub success: bool,
    pub summary: String,
    pub alerts: Vec<BackgroundAlert>,
    pub duration_ms: u64,
}

/// An alert generated by a background task.
#[derive(Debug, Clone)]
pub struct BackgroundAlert {
    pub title: String,
    pub message: String,
    pub priority: TaskPriority,
}

/// Scheduler for background intelligence tasks.
#[derive(Debug)]
pub struct BackgroundScheduler {
    tasks: Vec<ScheduledTask>,
    last_run: HashMap<String, Instant>,
    last_user_message: Instant,
    running: bool,
    paused: bool,
}

impl Default for BackgroundScheduler {
    fn default() -> Self {
        Self::new()
    }
}

impl BackgroundScheduler {
    pub fn new() -> Self {
        let mut scheduler = Self {
            tasks: Vec::new(),
            last_run: HashMap::new(),
            last_user_message: Instant::now(),
            running: false,
            paused: false,
        };
        scheduler.register_defaults();
        scheduler
    }

    /// Register the default background tasks.
    fn register_defaults(&mut self) {
        self.register(ScheduledTask {
            name: "vulnerability_scan".into(),
            interval: Duration::from_secs(4 * 3600), // 4 hours
            priority: TaskPriority::Low,
            task_type: BackgroundTaskType::VulnerabilityScan,
        });
        self.register(ScheduledTask {
            name: "memory_consolidation".into(),
            interval: Duration::from_secs(1800), // 30 min
            priority: TaskPriority::Normal,
            task_type: BackgroundTaskType::MemoryConsolidation,
        });
        self.register(ScheduledTask {
            name: "pattern_crystallization".into(),
            interval: Duration::from_secs(3600), // 1 hour
            priority: TaskPriority::Normal,
            task_type: BackgroundTaskType::PatternCrystallization,
        });
        self.register(ScheduledTask {
            name: "belief_audit".into(),
            interval: Duration::from_secs(24 * 3600), // 24 hours
            priority: TaskPriority::Low,
            task_type: BackgroundTaskType::BeliefAudit,
        });
        self.register(ScheduledTask {
            name: "codebase_index".into(),
            interval: Duration::from_secs(600), // 10 minutes
            priority: TaskPriority::Normal,
            task_type: BackgroundTaskType::CodebaseIndex,
        });
        self.register(ScheduledTask {
            name: "competence_report".into(),
            interval: Duration::from_secs(7 * 24 * 3600), // weekly
            priority: TaskPriority::Low,
            task_type: BackgroundTaskType::CompetenceReport,
        });
    }

    /// Register a new background task.
    pub fn register(&mut self, task: ScheduledTask) {
        self.tasks.push(task);
    }

    /// Notify that the user just sent a message.
    /// Pauses background work and records the timestamp.
    pub fn user_active(&mut self) {
        self.last_user_message = Instant::now();
        self.paused = true;
    }

    /// Notify that the cognitive loop finished processing.
    /// Resumes background work.
    pub fn user_idle(&mut self) {
        self.paused = false;
    }

    /// Get idle duration since last user message.
    pub fn idle_duration(&self) -> Duration {
        self.last_user_message.elapsed()
    }

    /// Determine which tasks are due to run given current idle state.
    pub fn due_tasks(&self) -> Vec<&ScheduledTask> {
        if self.paused || self.running { return vec![]; }

        let idle = self.idle_duration();
        let min_idle = Duration::from_secs(5);
        if idle < min_idle { return vec![]; }

        let mut due: Vec<&ScheduledTask> = self.tasks.iter().filter(|task| {
            // Check priority vs idle time
            let priority_ok = match task.priority {
                TaskPriority::Urgent => true,
                TaskPriority::Normal => idle >= Duration::from_secs(30),
                TaskPriority::Low => idle >= Duration::from_secs(300),
            };
            if !priority_ok { return false; }

            // Check if interval has elapsed since last run
            match self.last_run.get(&task.name) {
                Some(last) => last.elapsed() >= task.interval,
                None => true, // Never run before
            }
        }).collect();

        // Sort by priority (urgent first)
        due.sort_by(|a, b| a.priority.cmp(&b.priority));

        // Only return one task at a time
        due.truncate(1);
        due
    }

    /// Mark a task as having just run.
    pub fn mark_completed(&mut self, task_name: &str) {
        self.last_run.insert(task_name.to_string(), Instant::now());
        self.running = false;
    }

    /// Mark that a task is currently running.
    pub fn mark_running(&mut self) {
        self.running = true;
    }

    /// Get the number of registered tasks.
    pub fn task_count(&self) -> usize { self.tasks.len() }

    /// Get names of all registered tasks.
    pub fn task_names(&self) -> Vec<&str> {
        self.tasks.iter().map(|t| t.name.as_str()).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_new_scheduler_has_defaults() {
        let s = BackgroundScheduler::new();
        assert!(s.task_count() >= 6);
        assert!(s.task_names().contains(&"vulnerability_scan"));
        assert!(s.task_names().contains(&"memory_consolidation"));
    }

    #[test]
    fn test_no_tasks_when_paused() {
        let mut s = BackgroundScheduler::new();
        s.user_active();
        assert!(s.due_tasks().is_empty());
    }

    #[test]
    fn test_no_tasks_when_running() {
        let mut s = BackgroundScheduler::new();
        s.user_idle();
        s.mark_running();
        assert!(s.due_tasks().is_empty());
    }

    #[test]
    fn test_register_custom_task() {
        let mut s = BackgroundScheduler::new();
        let initial = s.task_count();
        s.register(ScheduledTask {
            name: "custom_check".into(),
            interval: Duration::from_secs(60),
            priority: TaskPriority::Urgent,
            task_type: BackgroundTaskType::Custom("check something".into()),
        });
        assert_eq!(s.task_count(), initial + 1);
    }

    #[test]
    fn test_mark_completed_prevents_immediate_rerun() {
        let mut s = BackgroundScheduler::new();
        s.user_idle();
        // Mark all tasks as just completed
        let names: Vec<String> = s.task_names().iter()
            .map(|n| n.to_string()).collect();
        for name in &names {
            s.mark_completed(name);
        }
        // Should be no due tasks now (intervals haven't elapsed)
        assert!(s.due_tasks().is_empty());
    }

    #[test]
    fn test_idle_duration_tracking() {
        let mut s = BackgroundScheduler::new();
        s.user_active();
        std::thread::sleep(Duration::from_millis(50));
        assert!(s.idle_duration() >= Duration::from_millis(50));
    }

    #[test]
    fn test_at_most_one_task_returned() {
        let mut s = BackgroundScheduler::new();
        s.user_idle();
        // Force long idle to make all tasks eligible
        s.last_user_message = Instant::now() - Duration::from_secs(86400);
        let due = s.due_tasks();
        assert!(due.len() <= 1);
    }
}
