//! V3 Part C: 28 orchestration coverage tests.
//! Every orchestration O0-O25 + Session 22/25 has at least one DirectCheck test
//! that calls its real public API. No stubs, no placeholders.

use super::bank::{V3Category, EvalMethod, V3Test};

/// 28 orchestration tests: 4 categories × 7 tests.
pub fn orch_tests() -> Vec<V3Test> {
    vec![
        // ── ORCH:FOUNDATION (7) — Core pipeline orchestrations ──
        V3Test { id: "orch-assume", name: "O0: Assumption mining", category: V3Category::OrchFoundation,
            eval_method: EvalMethod::DirectCheck, input: "delete production database",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-decompose", name: "O1: Task decomposition", category: V3Category::OrchFoundation,
            eval_method: EvalMethod::DirectCheck, input: "create a hello world file called test.txt",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-dag", name: "O1: DAG cycle detection", category: V3Category::OrchFoundation,
            eval_method: EvalMethod::DirectCheck, input: "cyclic_dag_test",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-feedback", name: "O3: Genome feedback loop", category: V3Category::OrchFoundation,
            eval_method: EvalMethod::DirectCheck, input: "feedback_test",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-skills", name: "O4: Skill operations", category: V3Category::OrchFoundation,
            eval_method: EvalMethod::DirectCheck, input: "skills_load",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-workspace", name: "O7: Workspace save+load", category: V3Category::OrchFoundation,
            eval_method: EvalMethod::DirectCheck, input: "workspace_roundtrip",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-discovery", name: "S22: Capability discovery", category: V3Category::OrchFoundation,
            eval_method: EvalMethod::DirectCheck, input: "help me with this task",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },

        // ── ORCH:EXECUTION (7) — Code, quality, parallel ──
        V3Test { id: "orch-critic", name: "O5: Quality evaluation", category: V3Category::OrchExecution,
            eval_method: EvalMethod::DirectCheck, input: "fn main() { println!(\"hello\"); }",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-critic-loop", name: "O5: Evaluate-revise cycle", category: V3Category::OrchExecution,
            eval_method: EvalMethod::DirectCheck, input: "fn add(a: i32, b: i32) -> i32 { a + b }",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-parallel", name: "O8: Parallel level analysis", category: V3Category::OrchExecution,
            eval_method: EvalMethod::DirectCheck, input: "parallel_levels",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-coder", name: "O9: Codebase analysis", category: V3Category::OrchExecution,
            eval_method: EvalMethod::DirectCheck, input: ".",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-zerodefect", name: "O10: Zero-defect construct", category: V3Category::OrchExecution,
            eval_method: EvalMethod::DirectCheck, input: "zerodefect_check",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-worker", name: "O6: Worker module", category: V3Category::OrchExecution,
            eval_method: EvalMethod::DirectCheck, input: "worker_check",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-evolution", name: "S25: Evolution engine", category: V3Category::OrchExecution,
            eval_method: EvalMethod::DirectCheck, input: "evolution_tick",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },

        // ── ORCH:INTELLIGENCE (7) — Learning, social, adaptivity ──
        V3Test { id: "orch-sentiment", name: "O11: Sentiment detection", category: V3Category::OrchIntelligence,
            eval_method: EvalMethod::DirectCheck, input: "I'm really frustrated with this broken code",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-social", name: "O11: Social context", category: V3Category::OrchIntelligence,
            eval_method: EvalMethod::DirectCheck, input: "Hey team, urgent: the deploy is broken",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-immerse", name: "O14: Domain mastery", category: V3Category::OrchIntelligence,
            eval_method: EvalMethod::DirectCheck, input: "rust",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-collab-idle", name: "O15: Collaboration idle", category: V3Category::OrchIntelligence,
            eval_method: EvalMethod::DirectCheck, input: "collab_idle",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-collab-test", name: "O15: Companion files", category: V3Category::OrchIntelligence,
            eval_method: EvalMethod::DirectCheck, input: "src/main.rs",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-usermodel", name: "O21: User model learning", category: V3Category::OrchIntelligence,
            eval_method: EvalMethod::DirectCheck, input: "user_model_observe",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-richfull", name: "O22: Rich output extract", category: V3Category::OrchIntelligence,
            eval_method: EvalMethod::DirectCheck,
            input: "| Col1 | Col2 |\n|---|---|\n| A | B |",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },

        // ── ORCH:PRESENCE (7) — External interfaces, monitor, remote ──
        V3Test { id: "orch-monitor", name: "O16: Monitor hub", category: V3Category::OrchPresence,
            eval_method: EvalMethod::DirectCheck, input: "monitor_hub",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-remote", name: "O18: Remote PIN verify", category: V3Category::OrchPresence,
            eval_method: EvalMethod::DirectCheck, input: "remote_pin",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-voice", name: "O17: Wake word detector", category: V3Category::OrchPresence,
            eval_method: EvalMethod::DirectCheck, input: "voice_check",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-spatial", name: "O19: Spatial presence", category: V3Category::OrchPresence,
            eval_method: EvalMethod::DirectCheck, input: "spatial_check",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-document", name: "O20: Document vision", category: V3Category::OrchPresence,
            eval_method: EvalMethod::DirectCheck, input: "document_check",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-antidetect", name: "O12: Anti-detection", category: V3Category::OrchPresence,
            eval_method: EvalMethod::DirectCheck, input: "antidetect_check",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-aesthetic", name: "O13: Aesthetic scoring", category: V3Category::OrchPresence,
            eval_method: EvalMethod::DirectCheck,
            input: "<html><body style='background:#fff;color:#333'><h1>Hello</h1></body></html>",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        // ── O26: Application Mind Model (AMM) + 6-Layer Stack ──
        V3Test { id: "orch-perception", name: "O26: Differential perception", category: V3Category::OrchPresence,
            eval_method: EvalMethod::DirectCheck, input: "perception_field",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-amm", name: "O26: App Mind Model", category: V3Category::OrchPresence,
            eval_method: EvalMethod::DirectCheck, input: "app_model",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-convention", name: "O26: Convention engine", category: V3Category::OrchIntelligence,
            eval_method: EvalMethod::DirectCheck, input: "convention_resolve",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-kinematic", name: "O26: Fitts's Law motor", category: V3Category::OrchExecution,
            eval_method: EvalMethod::DirectCheck, input: "fitts_law_motor",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-verify", name: "O26: Cascade verification", category: V3Category::OrchPresence,
            eval_method: EvalMethod::DirectCheck, input: "verification_cascade",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-muscle", name: "O26: Muscle memory", category: V3Category::OrchIntelligence,
            eval_method: EvalMethod::DirectCheck, input: "muscle_memory",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        // ── O27-O32: Complete Autonomous Entity ──
        V3Test { id: "orch-intent-compile", name: "O27: Intent compiler", category: V3Category::OrchIntelligence,
            eval_method: EvalMethod::DirectCheck, input: "intent_compiler",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-consequence", name: "O28: Consequence prediction", category: V3Category::OrchIntelligence,
            eval_method: EvalMethod::DirectCheck, input: "consequence_predict",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-autonomy", name: "O29: Autonomy gradient", category: V3Category::OrchExecution,
            eval_method: EvalMethod::DirectCheck, input: "autonomy_gradient",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-recovery", name: "O30: Recovery loop", category: V3Category::OrchExecution,
            eval_method: EvalMethod::DirectCheck, input: "recovery_loop",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-proactive", name: "O31: Proactive initiation", category: V3Category::OrchIntelligence,
            eval_method: EvalMethod::DirectCheck, input: "proactive_engine",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
        V3Test { id: "orch-quality", name: "O32: Quality judgment", category: V3Category::OrchExecution,
            eval_method: EvalMethod::DirectCheck, input: "quality_judge",
            pass_contains: &[], fail_contains: &[], min_hour: 0, timeout_secs: 60 },
    ]
}
