//! SkillGenerator — writes TOML skill packages from observed patterns.
//! Output format: SKILL-FORMAT-SPEC.md
//! Generated format == hand-written format. Always.

use crate::{errors::AutomationError, pattern::BehaviorPattern};

/// The generated skill package — TOML content for each file.
#[derive(Debug, Clone)]
pub struct GeneratedSkillPackage {
    pub skill_name: String,
    pub skill_toml: String,
    pub vocab_toml: String,
    pub functor_toml: String,
    pub actions_toml: String,
    pub env_toml: String,
    pub genome_toml: String,
}

impl GeneratedSkillPackage {
    /// True if all required files have content.
    pub fn is_valid(&self) -> bool {
        !self.skill_name.is_empty() && !self.skill_toml.is_empty() && !self.actions_toml.is_empty()
    }

    /// Summary for TUI / logging.
    pub fn summary(&self) -> String {
        format!("skill '{}' generated (6 TOML files)", self.skill_name)
    }
}

/// Generates a skill package from a behavior pattern.
pub struct SkillGenerator;

impl SkillGenerator {
    pub fn new() -> Self {
        Self
    }

    /// Generate a complete skill package from a pattern.
    pub fn generate(
        &self,
        pattern: &BehaviorPattern,
    ) -> Result<GeneratedSkillPackage, AutomationError> {
        let skill_name = self.skill_name_from_pattern(pattern);

        Ok(GeneratedSkillPackage {
            skill_name: skill_name.clone(),
            skill_toml: self.gen_skill_toml(&skill_name, pattern),
            vocab_toml: self.gen_vocab_toml(pattern),
            functor_toml: self.gen_functor_toml(pattern),
            actions_toml: self.gen_actions_toml(pattern),
            env_toml: self.gen_env_toml(pattern),
            genome_toml: self.gen_genome_toml(pattern),
        })
    }

    fn skill_name_from_pattern(&self, pattern: &BehaviorPattern) -> String {
        // Convert "deploy.staging" -> "auto-deploy-staging"
        let base = pattern.action_id.replace(['.', '_'], "-").to_lowercase();
        format!("auto-{}", base)
    }

    fn gen_skill_toml(&self, name: &str, pattern: &BehaviorPattern) -> String {
        format!(
            r#"# Auto-generated by hydra-automation
# Source: {} observations of '{}'

[skill]
name        = "{}"
version     = "0.1.0"
description = "Auto-crystallized from {} observed executions"
author      = "hydra-automation"
domains     = ["{}"]

[requires]
layers = [1, 3]

[provides]
capabilities = ["{}"]

[generation]
auto_generatable = true
source_pattern   = "{}"
observations     = {}
success_rate     = {:.2}
"#,
            pattern.count,
            pattern.action_id,
            name,
            pattern.count,
            pattern.domain,
            pattern.action_id,
            pattern.signature,
            pattern.count,
            pattern.success_rate,
        )
    }

    fn gen_vocab_toml(&self, pattern: &BehaviorPattern) -> String {
        // Extract keywords from action_id and intent patterns
        let keywords: Vec<String> = pattern
            .action_id
            .split('.')
            .chain(pattern.domain.split('-'))
            .map(|w| format!("\"{}\"", w))
            .collect();

        format!(
            r#"# Auto-generated vocabulary

[domain.{}]
keywords = [{}]
"#,
            pattern.domain,
            keywords.join(", "),
        )
    }

    fn gen_functor_toml(&self, pattern: &BehaviorPattern) -> String {
        format!(
            r#"# Auto-generated functor mappings

[[mapping]]
trigger    = ["{}"]
primitives = ["optimization", "dependency"]
notes      = "Auto-crystallized from observed behavior"
"#,
            pattern.action_id,
        )
    }

    fn gen_actions_toml(&self, pattern: &BehaviorPattern) -> String {
        // Build param list from common params
        let params: String = if pattern.common_params.is_empty() {
            String::new()
        } else {
            pattern
                .common_params
                .keys()
                .map(|k| {
                    format!(
                        "\n    {{ name = \"{}\", type = \"string\", required = false }}",
                        k
                    )
                })
                .collect::<Vec<_>>()
                .join(",")
        };

        format!(
            r#"# Auto-generated actions

[[action]]
id = "{}"
description = "Auto-crystallized: {}"
verb = "automating"
executor = "internal"
reversible = false
receipt = true
estimated_ms = {}
input_params = [{}]
"#,
            pattern.action_id, pattern.action_id, pattern.avg_duration_ms as u64, params,
        )
    }

    fn gen_env_toml(&self, _pattern: &BehaviorPattern) -> String {
        r#"# Auto-generated environment requirements

[runtime]
min_memory_mb = 256
min_disk_mb   = 512

[plasticity]
low_resource_mode      = true
low_resource_threshold_mb = 128
"#
        .to_string()
    }

    fn gen_genome_toml(&self, pattern: &BehaviorPattern) -> String {
        format!(
            r#"# Auto-generated genome seeds
# Source: {} observed successful executions

[[entry]]
situation  = "{} {} pattern"
approach   = "execute {} directly"
confidence = {:.2}
notes      = "Auto-crystallized: {:.0}% success over {} observations"
"#,
            pattern.count,
            pattern.action_id,
            pattern.domain,
            pattern.action_id,
            pattern.success_rate,
            pattern.success_rate * 100.0,
            pattern.count,
        )
    }
}

impl Default for SkillGenerator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::observation::ExecutionObservation;
    use std::collections::HashMap;

    fn make_crystallizable_pattern() -> BehaviorPattern {
        let obs = ExecutionObservation::new(
            "deploy.staging",
            "deploy to staging",
            HashMap::new(),
            "engineering",
            1200,
            true,
        );
        let mut p = BehaviorPattern::new(&obs);
        for _ in 1..crate::constants::CRYSTALLIZATION_THRESHOLD {
            let o = ExecutionObservation::new(
                "deploy.staging",
                "deploy to staging",
                HashMap::new(),
                "engineering",
                1100,
                true,
            );
            p.add_observation(&o);
        }
        p
    }

    #[test]
    fn generates_valid_package() {
        let gen = SkillGenerator::new();
        let pattern = make_crystallizable_pattern();
        let pkg = gen.generate(&pattern).expect("generate should succeed");
        assert!(pkg.is_valid());
        assert!(pkg.skill_name.starts_with("auto-"));
    }

    #[test]
    fn skill_toml_contains_version() {
        let gen = SkillGenerator::new();
        let p = make_crystallizable_pattern();
        let pkg = gen.generate(&p).expect("generate should succeed");
        assert!(pkg.skill_toml.contains("version"));
        assert!(pkg.skill_toml.contains("0.1.0"));
    }

    #[test]
    fn actions_toml_contains_action_id() {
        let gen = SkillGenerator::new();
        let p = make_crystallizable_pattern();
        let pkg = gen.generate(&p).expect("generate should succeed");
        assert!(pkg.actions_toml.contains("deploy.staging"));
    }

    #[test]
    fn genome_toml_contains_success_rate() {
        let gen = SkillGenerator::new();
        let p = make_crystallizable_pattern();
        let pkg = gen.generate(&p).expect("generate should succeed");
        assert!(pkg.genome_toml.contains("confidence"));
    }

    #[test]
    fn summary_non_empty() {
        let gen = SkillGenerator::new();
        let p = make_crystallizable_pattern();
        let pkg = gen.generate(&p).expect("generate should succeed");
        assert!(!pkg.summary().is_empty());
    }
}
